# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='save_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convert_from', models.TextField()),
                ('convert_to', models.TextField()),
                ('amount', models.TextField()),
            ],
        ),
    ]
